FROM resin/%%RESIN_MACHINE_NAME%%-debian

#switch on systemd init system in container
ENV INITSYSTEM on

RUN apt-get -q update && apt-get install -yq --no-install-recommends build-essential cmake && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /usr/src/app
WORKDIR /usr/src/app/libdweetAgent


RUN mkdir mybuild && cd mybuild && mkdir make && cmake .. make
RUN make install

WORKDIR /usr/src/app/libdweetAgent/Examples

RUN ./dweetWriter

#RUN gcc -o main main.c

#CMD ./main